### PR TITLE
Draft

### PR DESCRIPTION
**Pull request by s-newman**
This is the draft of the constitution, ported over from Google Docs. Minimal changes have been made:
- Cross-references have been updated
- Section symbol has been removed from cross-references
- Article numbering has been fixed
- References to "Club Advisors" have been removed from the terms
- Cross-reference to non-existent absences section has been removed

Please note that **PDFs are not tracked** in this repository because they are build artifacts. PDF copies should be made available through other means, such as on the club website.

### CODE REVIEW

**Comment by Cictrone** [comment]
I believe https://github.com/ritsec/constitution/blob/cd6378aebe69a81691e0d9bad9dd3e2cacc3d76a/bylaws/programs/01-interest-group.tex#L57
maybe a typo, it should be `voted by EBoard`.

**Comment by Cictrone** [comment]
😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍

**Review by hulto — DISMISSED** [review]
I

**Review by Cictrone — APPROVED** [review]
XD

**Review by nullmonk — APPROVED** [review]

**Pull request merged**
